#!/bin/bash

FS=$(df -H | grep -v -E 'Filesystem|tmpfs|efivarfs' | grep -e boot | awk '{print $5}' | tr -d %)

if [[ $FS -ge 80 ]]
then
	echo "WARNING, disk space is low"
else
	echo "Disk space is under limit"
fi


