#!/bin/bash

function factorial(){
	factorial=1
	i=1
	num=$1
	while [ $i -le $num ];do
		factorial=$((factorial*i))
		((i++))
	done
	return $factorial
}

read -p "Give number:- " num
echo $(factorial $num )
